project:
  type: book

author:
  - name: Sean Davis
    url: https://seandavi.github.io/
    affiliation: University of Colorado<br/>Anschutz School of Medicine
    affiliation-url: https://medschool.cuanschutz.edu/
    email: seandavi@gmail.com
citation:
  url: https://seandavi.github.io/RBiocBook
date: "2024-06-01"
date-modified: 'last-modified'
description: |
  A collection of chapters more than a book, but....
execute:
  freeze: auto

book:
  google-analytics: "G-KLLV1GCF4E"
  title: "The RBioc Book"
  date: "today"
  search: true
  repo-url: https://github.com/seandavi/RBiocBook
  url: https://seandavi.github.io/RBiocBook
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  page-navigation: true
  reader-mode: true

  navbar:
    title: "The RBioc Book"
    left:
      - href: index.qmd
        text: Home
      - text: "Introduction"
        href: intro.qmd
      - text: "Data Structures"
        href: data_structures_overview.qmd

      - text: "talk"
        href: stuff.qmd


  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - intro.qmd
        - intro_to_rstudio.qmd
        - r_intro_mechanics.qmd
        - r_basics.qmd
        - packages_and_dice.qmd
        - reading_and_writing.qmd
    - part: data_structures_overview.qmd
      chapters:
        - vectors.qmd
        - matrices.qmd
        - lists.qmd
        - dataframes_intro.qmd
        - factors.qmd

    - part: eda_overview.qmd
      chapters:
        - dplyr_intro_msleep.qmd
        - eda_and_univariate_brfss.qmd
        - visualization_guide.qmd

    - part: statististics
      chapters:
        #- working_with_distributions.qmd
        - norm.qmd
        - t-stats-and-tests.qmd
        - kmeans.qmd

    - part: "Machine Learning"
      chapters:
        - machine_learning/intro.qmd
        - machine_learning/models.qmd
        - machine_learning/mlr3verse_intro.qmd
        - machine_learning/machine_learning_mlr3.qmd

    - part: "Bioconductor"
      chapters:
        - geoquery.qmd
        - bioc-summarizedexperiment.qmd
        - ranges_and_signals.qmd
        #- ranges_exercises.qmd
        - atac-seq/atac-seq.qmd
        #- single-cell-atac-and-rna-transfer-learning.qmd
    # - part: "Single Cell"
    #   chapters:
    #     - single_cell/setup.qmd
    
    - references.qmd

  appendices:
    - appendix.qmd
    - git_and_github.qmd
    - additional_resources.qmd
    - ai_tools.qmd
    - dataviz.qmd
    - matrix_exercises.qmd
    #- part: "Bioconductor"
    #chapters:
    #- bioconductor_intro.qmd
    #- bioconductor_packages.qmd
  page-footer:
    center:
      - text: "License"
        href: license.qmd

bibliography: bibliography.bib

format:
  html:
    code-tools:
      source: repo
    fig-cap-location: margin
    tbl-cap-location: margin
    code-copy: true
    theme:
      light: [cosmo]
    #fontsize: "15px"
    linestretch: 1.8
    #mainfont: "Roboto"
    #monofont: "Fira Mono"
    smooth-scroll: true
    toc-depth: 3
    code-link: true
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral
  titlepage-pdf:
    titlepage: academic
    linkcolor: blue
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    # tbl-cap-location: margin
    # fig-cap-location: margin
    lot: true
    lof: true
    # insert index entries: Markdown\index{Markdown} allows you to write ...
    include-in-header:
      text: |
        \usepackage{makeidx}
        \usepackage{hyperref}
        \makeindex
    include-after-body:
      text: |
        \printindex
  epub:
    cover-image: images/cover.png
