project:
  type: book


author:
  - name: Sean Davis
    url: https://seandavi.github.io/
    affiliation: University of Colorado<br/>Anschutz School of Medicine
    affiliation-url: https://medschool.cuanschutz.edu/
    email: seandavi@gmail.com
citation:
  url: https://example.com/summarizing-output
date: "today"
description: |
  This is the really long description.

execute:
  freeze: auto

book:
  title: "mybook"
  date: "today"
  search: true
  repo-url: https://github.com/seandavi/CSHLDataCourse
  url: https://github.com/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  page-navigation: true

  chapters:
    - preface.qmd
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
        - r_intro_mechanics.qmd
        - r_basics.qmd
    - part: data_structures_overview.qmd
      chapters:
        - vectors.qmd
        - matrices.qmd
        - dataframes_intro.qmd
        - factors.qmd

    - part: eda_overview.qmd
      chapters:
        - eda_and_univariate_brfss.qmd

    - part: statististics
      chapters:
        - t-stats-and-tests.qmd
        - kmeans.qmd

    - part: "Bioconductor"
      chapters:
        - bioc-summarizedexperiment.qmd
    - references.qmd

  appendices:
    - appendix.qmd
    - additional_resources.qmd
    #- part: "Bioconductor"
      #chapters:
        #- bioconductor_intro.qmd
        #- bioconductor_packages.qmd
  navbar:
    right:
      - icon: github
        aria-label: GitHub
  page-footer:
    center: 
      - text: "License"
        href: license.qmd

#bibliography: references.bib
bibliography: bibliography.bib

format:

  html:
    code-tools:
      source: repo
    fig-cap-location: margin
    tbl-cap-location: margin
    code-copy: true
    theme:
      light: yeti
      dark: cyborg
  titlepage-pdf:
    titlepage: academic
    linkcolor: blue
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    fontfamily: libertinus
    tbl-cap-location: margin
    fig-cap-location: margin
    lot: true
    lof: true
    # insert index entries: Markdown\index{Markdown} allows you to write ...
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \usepackage{hyperref}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/cover.png 
